[package]
name = "latka"
version = "0.0.1"
authors = ["Fenimore Love <exorable.ludos@gmail.com>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
tempfile = "3.0.7" # test dependency
byteorder = "1.3.1"